version: '3'
services:
  app:
    build: ./app
    ports:
      - "5001-5010:5000"
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
